language: php

sudo: required

matrix:
  include:
    - php: 7.3
      env: SW_VERSION="4.6.0"
    - php: 7.4
      env: SW_VERSION="4.6.0"

services:
  - mysql
  - redis
  - docker

before_install:
  - export PHP_MAJOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 1)"
  - export PHP_MINOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 2)"
  - echo $PHP_MAJOR
  - echo $PHP_MINOR

install:
  - cd $TRAVIS_BUILD_DIR
  - bash .travis/swoole.install.sh
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - phpenv config-add .travis/ci.ini
  - bash .travis/setup.mysql.sh
  - cp .travis/.env.example .env
  - docker run -d --name dev-consul -e CONSUL_BIND_INTERFACE=eth0 -p 8500:8500 consul
  - docker run --name nsq -p 4150:4150 -p 4151:4151 -p 4160:4160 -p 4161:4161 -p 4170:4170 -p 4171:4171 --entrypoint /bin/nsqd -d nsqio/nsq:latest
  - docker build --tag grpc-server:latest src/grpc-client/tests/Mock
  - docker run -d --name grpc-server -p 50051:50051 grpc-server:latest

before_script:
  - cd $TRAVIS_BUILD_DIR
  - composer config -g process-timeout 900 && composer update -o

script:
  - composer analyse src
  - composer test -- --exclude-group NonCoroutine
  - vendor/bin/phpunit --group NonCoroutine

notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=72c12e591c435f0f41e09261f6252aeafd284e432657b1f8d4a77b5aac8fbfcd
